# Generated by Django 3.2.19 on 2023-08-23 16:42

from django.db import migrations


def identify_new_buildings(apps, shcema_editor):
    Flat = apps.get_model('property', 'Flat')
    for apartments in Flat.objects.all():
        if apartments.construction_year >= 2015:
            apartments.new_building = True
            apartments.save()
        elif apartments.construction_year < 2015:
            apartments.new_building = False
            apartments.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(identify_new_buildings),
    ]
