# Generated by Django 2.2.24 on 2023-07-15 16:59

from django.db import migrations


def connect_owner_and_flat(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for owner in Owner.objects.all().iterator():
        flats = Flat.objects.filter(owner=owner.full_name)
        owner.flats.set(flats)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20230824_2111'),
    ]

    operations = [
        migrations.RunPython(connect_owner_and_flat)
    ]